services:

  auth-service-db:
    image: postgres
    container_name: auth-service-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: auth-db
    ports:
      - 5432:5432
    networks:
      - local

  auth-service-migrate:
    image: migrate/migrate
    restart: on-failure:5
    command:
      - "-path=/migrations/auth"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-service-db:5432/auth-db?sslmode=disable"
      - "up"
    volumes:
      - ./migrations/auth:/migrations/auth
    networks:
      - local
    depends_on:
      - auth-service-db

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    environment:
      ENVIRONMENT: local
      STORAGE_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-service-db:5432/auth-db?sslmode=disable"
    ports:
      - 80:80
    restart: on-failure:5
    networks:
      - local
    depends_on:
      - auth-service-db
      - auth-service-migrate

networks:
  local:
    name: local
    driver: bridge