services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - local
    depends_on:
      - auth-service-db
      - auth-service-migrate

  auth-service-db:
    image: postgres
    container_name: auth-service-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: auth-db
    ports:
      - '5432:5432'
    networks:
      - local

  auth-service-migrate:
    image: migrate/migrate
    command:
      - "-path=/migrations/auth"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-service-db:5432/auth-db?sslmode=disable"
      - "up"
    volumes:
      - ./migrations/auth:/migrations/auth
    networks:
      - local
    depends_on:
      - auth-service-db

networks:
  local:
    name: local
    driver: bridge