version: '3.9'
services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - local
networks:
  local:
    name: local
    driver: bridge